"""
Django settings for usst_info project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5+#e!qb&__x9od!hjt)-*z^@al6=#19dc4pe558jy31o))ik!c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [u'127.0.0.1',u'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'search',
    'user',
    'qa',
]

HAYSTACK_CONNECTIONS={
    'default':{
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usst_info.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usst_info.global_variable.variables'
            ],
        },
    },
]

WSGI_APPLICATION = 'usst_info.wsgi.application'

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jelly',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'',
        'PORT':'3306',
    }
}
AUTH_USER_MODEL='user.Userinfo'

AUTHENTICATION_BACKENDS = (
    'user.auth.MyBackend',
)
# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

colleges=['',
         '能源与动力工程学院',
         '光电信息与计算机工程学院',
         '管理学院',
         '机械学院',
         '外语学院',
         '环境与建筑学院',
         '医疗器械与食品学院',
         '出版印刷与艺术学院',
         '理学院',
         '中德学院',
         '中英国际学院',
         '材料科学与工程学院']

majors=['',
        ['未分专业',
         '过程装备与控制工程',
         '新能源科学与工程',
         '能源与动力工程'],
        ['未分专业',
         '测控技术与仪器',
         '电子信息工程',
         '通信工程',
         '电子科学与技术',
         '智能科学与技术',
         '计算机科学与技术',
         '网络工程',
         '电气工程及其自动化',
         '自动化',
         '光电信息科学与工程',
         '光电信息科学与工程（中德合作）'],
        ['未分专业',
         '国际经济与贸易',
         '金融学',
         '管理学科',
         '信息管理与信息系统',
         '工业工程',
         '工商管理（中美合作）',
         '会计学',
         '公共事业管理',
         '公共事业管理（体育）',
         '税收学'],
        ['未分专业',
         '机械设计制造及其自动化',
         '车辆工程',
         '机械设计制造及其自动化（中德合作）'],
        ['未分专业',
         '土木工程',
         '环境工程',
         '建筑环境与能源应用工程'],
        ['未分专业',
         '生物医学工程',
         '食品科学与工程',
         '食品质量与安全',
         '医学影像技术',
         '医学信息工程',
         '制药工程',
         '假肢矫形工程'],
        ['未分专业',
         '广告学',
         '编辑出版学',
         '传播学',
         '包装工程',
         '工业设计',
         '动画',
         '视觉传达设计',
         '产品设计',
         '环境设计',
         '印刷工程（卓越班）'],
        ['未分专业',
         '数学与应用数学',
         '应用物理学',
         '应用化学'],
        ['未分专业',
         '电气工程及其自动化'],
        ['未分专业',
         '电子信息科学与技术',
         '机械设计及其自动化（中英合作）',
         '会展经济与管理（中英合作）',
         '工商管理'],
        ['未分专业',
         '材料科学与工程',
         '材料科学与工程（卓越班）',
         '材料成型及控制工程']]