# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('if_read', models.IntegerField(default=0)),
                ('if_delete', models.IntegerField(default=0)),
                ('aswerer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('if_reply', models.IntegerField(default=0)),
                ('if_read', models.IntegerField(default=0)),
                ('if_delete', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.Answer')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_reply', to=settings.AUTH_USER_MODEL)),
                ('reply_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qa.Comment')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accept_reply', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=100)),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('if_delete', models.IntegerField(default=0)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('categories', models.TextField()),
                ('if_delete', models.IntegerField(default=0)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Updown',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('if_up', models.IntegerField()),
                ('if_ans', models.IntegerField()),
                ('ac_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'updown',
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.Question'),
        ),
    ]
