# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170818_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_active',
            new_name='if_delete',
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
