# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170822_1647'),
        ('user', '0003_auto_20170818_1344'),
    ]

    operations = [
    ]
